CITY_BUCKET_MAP = {
    "Delhi-Metro": [
        "Bahadurgarh",
        "Bhiwadi",
        "Delhi",
        "Faridabad",
        "Gautam Buddha Nagar",
        "Ghaziabad",
        "Gurgaon",
        "Gurugram",
        "Modinagar",
        "Muradnagar",
        "Neemrana",
        "Noida",
        "Noida 1",
        "Shahdara",
    ],
    "Mumbai-Metro": [
        "Mumbai",
    ],
    "Bengaluru-Metro": [
        "Bangalore",
        "Bengaluru",
        "Bengaluru Rural",
        "Ramanagar",
    ],
    "Kolkata-Metro": [
        "Asansol",
        "Bankura",
        "Bardhaman",
        "Birbhum",
        "Bishnupur",
        "Bolpur",
        "Cooch Behar",
        "Darjeeling",
        "Darjiling",
        "Durgapur",
        "East Midnapore",
        "Hooghly",
        "Howrah",
        "Jalpaiguri",
        "Kharagpur",
        "Kolkata",
        "Malda",
        "Murshidabad",
        "Nadia",
        "North 24 Parganas",
        "North Dinajpur",
        "Puruliya",
        "Siliguri",
        "South 24 Parganas",
        "South Dinajpur",
        "West Midnapore",
    ],
    "Hyderabad-Metro": [
        "Adilabad",
        "Bhongir",
        "Gadwal",
        "Hanamkonda",
        "Hyderabad",
        "Jagtial",
        "Jangaon",
        "Jayashankar",
        "Kamareddy",
        "Karim Nagar",
        "Karimnagar",
        "Khammam",
        "Kothagudem",
        "Kothagudem Colls",
        "Mahabub Nagar",
        "Mancherial",
        "Medak",
        "Nagar Kurnool",
        "Nalgonda",
        "Nirmal",
        "Nizamabad",
        "Parkal",
        "Peddapalli",
        "Rangareddy",
        "Sangareddy",
        "Siddipet",
        "Sircilla",
        "Stn. Jadcherla",
        "Suryapet",
        "Trimulgherry",
        "Vikarabad",
        "Wanaparthy",
        "Warangal",
    ],
    "Chennai-Metro": [
        "Ariyalur",
        "Chennai",
        "Coimbatore",
        "Cuddalore",
        "Dharmapuri",
        "Dindigul",
        "Erode",
        "Hosur",
        "Kanchipuram",
        "Kanyakumari",
        "Karaikkudi",
        "Karaikudi",
        "Krishnagiri",
        "Madurai",
        "Nagapattinam",
        "Nagercoil",
        "Namakkal",
        "Nilgiris",
        "Perambalur",
        "Pudukkottai",
        "Ramanathapuram",
        "Salem",
        "Sivaganga",
        "Thanjavur",
        "Theni",
        "Thiruvallur",
        "Thoothukudi",
        "Tiruchirappalli",
        "Tirunelveli",
        "Tiruppur",
        "Tirupur",
        "Tiruvallur",
        "Tiruvannamalai",
        "Tiruvarur",
        "Trichy",
        "Tuticorin",
        "Vellore",
        "Villupuram",
        "Virudhunagar",
    ],
    "Pune-Metro": [
        "Ahmed Nagar",
        "Ahmednagar",
        "Akola",
        "Amravati",
        "Aurangabad",
        "Beed",
        "Bhandara",
        "Buldhana",
        "Chandrapur",
        "Chatrapati Sambhaji Nagar",
        "Dhule",
        "Gadchiroli",
        "Gondia",
        "Hingoli",
        "Jalgaon",
        "Jalna",
        "Kolhapur",
        "Latur",
        "Lonavala",
        "Lonavla",
        "Nagpur",
        "Nanded",
        "Nandurbar",
        "Nashik",
        "Osmanabad",
        "Parbhani",
        "Pune",
        "Ratnagiri",
        "Sangli",
        "Satara",
        "Shirdi",
        "Sindhudurg",
        "Solapur",
        "Wardha",
        "Washim",
        "Yavatmal",
    ],
    "Ahmedabad-Metro": [
        "Ahmedabad",
        "Anand",
        "Aravalli",
        "Banaskantha",
        "Gandhi Nagar",
        "Gandhidham",
        "Kalol",
        "Kheda",
        "Mahesana",
        "Mahisagar",
        "Mehsana",
        "Nadiad",
        "Patan",
        "Sabarkantha",
    ],
    "West-T2": [
        "Ajmer",
        "Alwar",
        "Ankleshwar",
        "Banswara",
        "Barmer",
        "Bharatpur",
        "Bharuch",
        "Bhavnagar",
        "Bhilwara",
        "Bhuj",
        "Bikaner",
        "Botab",
        "Bundi",
        "Central Goa",
        "Chhotaudepur",
        "Chittorgarh",
        "Dadra  Nagar Haveli",
        "Dahod",
        "Daman",
        "Dangs",
        "Dausa",
        "Devbhoomi Dwerka",
        "Dholpur",
        "Diu",
        "Dungarpur",
        "Gir Somnath",
        "Goa",
        "Hanumangarh",
        "Jaipur",
        "Jaisalmer",
        "Jalor",
        "Jamnagar",
        "Jhujhunu",
        "Jodhpur",
        "Junagadh",
        "Kachchh",
        "Karauli",
        "Kota",
        "Morbi",
        "Nagaur",
        "Narmada",
        "Navsari",
        "North Goa",
        "Pali",
        "Panch Mahals",
        "Porbandar",
        "Raipur",
        "Rajkot",
        "Rajsamand",
        "Sawai Madhopur",
        "Sikar",
        "Silvassa",
        "Sirohi",
        "South Goa",
        "Sri Ganganagar",
        "Sri_Ganganagar",
        "Surat",
        "Surendra Nagar",
        "Tapi",
        "Tonk",
        "Udaipur",
        "Vadodara",
        "Vadodra",
        "Valsad",
        "Vapi",
    ],
    "West-T3": [
        "Agar Malwa",
        "Alirajpur",
        "Amreli",
        "Anuppur",
        "Ashok Nagar",
        "Balaghat",
        "Balod",
        "Balod Bazer",
        "Baran",
        "Barwani",
        "Bastar",
        "Bemetara",
        "Betul",
        "Bhilai",
        "Bhind",
        "Bhopal",
        "Bijapur(Cgh)",
        "Bilaspur",
        "Bilaspurcgh",
        "Burhanpur",
        "Chhatarpur",
        "Chhindwara",
        "Churu",
        "Damoh",
        "Dantewada",
        "Datia",
        "Dewas",
        "Dhamtari",
        "Dhar",
        "Dindori",
        "Durg",
        "Gariaband",
        "Guna",
        "Gwalior",
        "Harda",
        "Hoshangabad",
        "Indore",
        "Jabalpur",
        "Jagdalpur",
        "Janjgirchampa",
        "Jhabua",
        "Jhalawar",
        "Kangra",
        "Kanker",
        "Katni",
        "Kawardha",
        "Khandwa",
        "Khargone",
        "Korba",
        "Koriya",
        "Mahasamund",
        "Mandla",
        "Mandsaur",
        "Morena",
        "Mungeli",
        "Narayanpur",
        "Narmadapuram",
        "Narsinghpur",
        "Neemuch",
        "Palanpur",
        "Panna",
        "Raigarh",
        "Raisen",
        "Rajgarh",
        "Rajnandgaon",
        "Ratlam",
        "Rewa",
        "Sagar",
        "Satna",
        "Sehore",
        "Seoni",
        "Shahdol",
        "Shajapur",
        "Sheopur",
        "Shivpuri",
        "Sidhi",
        "Singrauli",
        "Surajpur",
        "Surguja",
        "Tikamgarh",
        "Ujjain",
        "Umaria",
        "Vidisha",
    ],
    "North-T2": [
        "Agra",
        "Aligarh",
        "Allahabad",
        "Almora",
        "Ambala",
        "Ambedkar Nagar",
        "Amethi",
        "Amritsar",
        "Ananthnag",
        "Ayodhya",
        "Baddi",
        "Bageshwar",
        "Banka",
        "Baramulla",
        "Bareilly",
        "Batala",
        "Bathinda",
        "Begusarai",
        "Bettiah",
        "Bhagalpur",
        "Bhiwani",
        "Bihar Sharif",
        "Bilaspur Hp",
        "Bokaro",
        "Budgam",
        "Buxar",
        "Chamoli",
        "Champawat",
        "Chandigarh",
        "Chandighar",
        "Charkhi Dadri",
        "Chatra",
        "Darbhanga",
        "Dehradun",
        "Deoghar",
        "Dhanbad",
        "Dharamshala",
        "Doda",
        "Dumka",
        "East Singhbhum",
        "Faizabad",
        "Faridkot",
        "Fatehabad",
        "Fatehgarh Sahib",
        "Fazilka",
        "Firozabad",
        "Ganderbal",
        "Garhwa",
        "Gaya",
        "Ghazipur",
        "Giridh",
        "Giridih",
        "Godda",
        "Gorakhpur",
        "Gumla",
        "Gurdaspur",
        "Haldwani",
        "Hamirpur",
        "Hamirpurhp",
        "Haridwar",
        "Hazaribag",
        "Hazaribagh",
        "Hisar",
        "Hoshiarpur",
        "Jalandhar",
        "Jammu",
        "Jamshedpur",
        "Jamtara",
        "Jamui",
        "Jaspur",
        "Jehanabad",
        "Jhajjar",
        "Jind",
        "Kaithal",
        "Kanpur",
        "Kanpur Nagar",
        "Kapurthala",
        "Karnal",
        "Kashipur",
        "Kathua",
        "Katihar",
        "Khanna",
        "Kharar",
        "Khunti",
        "Koderma",
        "Kotdwar",
        "Kulgam",
        "Kullu",
        "Kupwara",
        "Kurukshetra",
        "Lakhisarai",
        "Latehar",
        "Leh",
        "Lohardaga",
        "Lucknow",
        "Ludhiana",
        "Madhubani",
        "Mahendragarh",
        "Manali",
        "Mandi",
        "Mansa",
        "Mathura",
        "Meerut",
        "Mewat",
        "Moga",
        "Mohali",
        "Moradabad",
        "Motihari",
        "Muktsar",
        "Munger",
        "Muzaffarnagar",
        "Muzaffarpur",
        "Muzzaffarnagar",
        "Nainital",
        "Nalanda",
        "Nawada",
        "Nawanshahr",
        "New Chandigarh",
        "NewChandigarh",
        "Pakur",
        "Palamau",
        "Palwal",
        "Panchkula",
        "Panipat",
        "Pathankot",
        "Patiala",
        "Patna",
        "Pauri Garhwal",
        "Phagwara",
        "Pinjore",
        "Pithoragarh",
        "Prayagraj",
        "Pulwama",
        "Purnia",
        "Raebareli",
        "Rajauri",
        "Rajpura",
        "Ramban",
        "Ramgarh",
        "Ranchi",
        "Reasi",
        "Rewari",
        "Rishikesh",
        "Rohtak",
        "Rohtas",
        "Roorke",
        "Roorkee",
        "Ropar",
        "Rudraprayag",
        "Rudrapur",
        "Rupnagar",
        "SAS Nagar",
        "Saharanpur",
        "Saharsa",
        "Sahibganj",
        "Samba",
        "Sangrur",
        "Seraikelakharsawan",
        "Sheikhpura",
        "Sheohar",
        "Shimla",
        "Shopian",
        "Simdega",
        "Sirsa",
        "Sitamarhi",
        "Siwan",
        "Solan",
        "Sonipat",
        "Srinagar",
        "Sultanpur",
        "Sundar Nagar",
        "Sundar_Nagar",
        "Supaul",
        "Tarn Taran",
        "Tehri Garhwal",
        "Udham Singh Nagar",
        "Udhampur",
        "Uttarkashi",
        "Vaishali",
        "Varanasi",
        "Vikasnagar",
        "Vrindavan",
        "West Singhbhum",
        "Yamunanagar",
        "Zirakpur",
    ],
    "North-T3": [
        "Amroha",
        "Araria",
        "Arwal",
        "Auraiya",
        "Azamgarh",
        "Bagpat",
        "Bahraich",
        "Ballia",
        "Balrampur",
        "Banda",
        "Barabanki",
        "Basti",
        "Bhojpur",
        "Bijnor",
        "Budaun",
        "Bulandshahr",
        "Chamba",
        "Chandauli",
        "Chitrakoot",
        "Deoria",
        "East Champaran",
        "Etah",
        "Etawah",
        "Farrukhabad",
        "Fatehpur",
        "Firozpur",
        "Gonda",
        "Gopalganj",
        "Hapur",
        "Hardoi",
        "Hathras",
        "Jalaun",
        "Jaunpur",
        "Jhansi",
        "Kaimur Bhabua",
        "Kannauj",
        "Kanpur Dehat",
        "Kanshiram Nagar",
        "Kaushambi",
        "Khagaria",
        "Kheri",
        "Kinnaur",
        "Kishanganj",
        "Kushinagar",
        "Lakhimpur",
        "Lalitpur",
        "Madhepura",
        "Maharajganj",
        "Mahoba",
        "Mahrajganj",
        "Mainpuri",
        "Mau",
        "Mirzapur",
        "Pilibhit",
        "Pratapgarh",
        "Pratapghar",
        "Rampur",
        "Samastipur",
        "Sambhal",
        "Sant Kabir Nagar",
        "Sant Ravidas Nagar",
        "Saran",
        "Shahjahanpur",
        "Shikohabad",
        "Shrawasti",
        "Siddharthnagar",
        "Sirmaur",
        "Sitapur",
        "Sonbhadra",
        "Una",
        "Unnao",
        "West Champaran",
    ],
    "East-T2": [
        "Aizawl",
        "Angul",
        "Baksa",
        "Balangir",
        "Baleswar",
        "Bargarh",
        "Barpeta",
        "Berhampur",
        "Bhadrak",
        "Bhubaneswar",
        "Bongaigaon",
        "Boudh",
        "Cachar",
        "Champhai",
        "Changlang",
        "Churachandpur",
        "Cuttack",
        "Darrang",
        "Debagarh",
        "Dhalai",
        "Dhemaji",
        "Dhenkanal",
        "Dhubri",
        "Dibrugarh",
        "Dima Hasso - North Cachar Hill",
        "Dimapur",
        "East Garo Hills",
        "East Kameng",
        "East Khasi Hills",
        "East Siang",
        "East Sikkim",
        "Gajapati",
        "Ganjam",
        "Goalpara",
        "Golaghat",
        "Guwahati",
        "Hailakandi",
        "Imphal East",
        "Imphal West",
        "Jagatsinghapur",
        "Jaintia Hills",
        "Jajapur",
        "Jharsuguda",
        "Jorhat",
        "Kalahandi",
        "Kamrup",
        "Kamrup Metropolitan",
        "Kandhamal",
        "Karbi Anglong",
        "Karimganj",
        "Kendrapara",
        "Kendujhar",
        "Khorda",
        "Kohima",
        "Kokrajhar",
        "Kolasib",
        "Koraput",
        "Lawngtlai",
        "Lohit",
        "Lower Dibang Valley",
        "Lower Subansiri",
        "Lunglei",
        "Malkangiri",
        "Mammit",
        "Marigaon",
        "Mayurbhanj",
        "Mokokchung",
        "Mon",
        "Nabarangapur",
        "Nagaon",
        "Nalbari",
        "Nayagarh",
        "North Sikkim",
        "North Tripura",
        "Nuapada",
        "Papum Pare",
        "Peren",
        "Puri",
        "Rayagada",
        "Ri Bhoi",
        "Saiha",
        "Sambalpur",
        "Senapati",
        "Sepahijala",
        "Serchhip",
        "Shillong",
        "Sibsagar",
        "Silchar",
        "Sonapur",
        "Sonitpur",
        "South Garo Hills",
        "South Sikkim",
        "South Tripura",
        "Sundergarh",
        "Tawang",
        "Thoubal",
        "Tinsukia",
        "Tirap",
        "Tuensang",
        "Udalguri",
        "Upper Subansiri",
        "West Garo Hills",
        "West Kameng",
        "West Khasi Hills",
        "West Siang",
        "West Sikkim",
        "West Tripura",
        "Wokha",
        "Zunhebotto",
    ],
    "South-T2": [
        "Alappuzha",
        "Anantapur",
        "Ananthapur",
        "Athani",
        "Bagalkot",
        "Bailhongal",
        "Ballari",
        "Belagavi",
        "Belgaum",
        "Belgavi",
        "Bellary",
        "Bhimavaram",
        "Bidar",
        "Bijapur",
        "Bijapur(Kar)",
        "Chamrajnagar",
        "Chickmagalur",
        "Chikkaballapur",
        "Chikkamagaluru",
        "Chitradurga",
        "Chittoor",
        "Dakshina Kannada",
        "Davanagere",
        "Davangere",
        "Devangere",
        "Dharwad",
        "East Godavari",
        "Eluru",
        "Ernakulam",
        "Gadag",
        "Gulbarga",
        "Guntur",
        "Hassan",
        "Haveri",
        "Hindupur",
        "Hosapete",
        "Hubballi",
        "Hubli",
        "Idukki",
        "Kadapa",
        "Kakinada",
        "Kalaburagi",
        "Kannur",
        "Karaikal",
        "Karur",
        "Kasargod",
        "Kochi",
        "Kodagu",
        "Kolar",
        "Kollam",
        "Koppal",
        "Kottayam",
        "Kovvur",
        "Kozhikode",
        "Krishna",
        "Kurnool",
        "Madanapalle",
        "Mahe",
        "Malappuram",
        "Mandya",
        "Mangalore",
        "Mangaluru",
        "Manipal",
        "Mysore",
        "Mysuru",
        "Nellore",
        "Ongole",
        "Palakkad",
        "Pathanamthitta",
        "Pondicherry",
        "Prakasam",
        "Puducherry",
        "Raichur",
        "Rajahmundry",
        "Shimoga",
        "Shivamogga",
        "Srikakulam",
        "Thiruvalla",
        "Thiruvananthapuram",
        "Thrissur",
        "Tirupati",
        "Trivandrum",
        "Tumakuru",
        "Tumkur",
        "Tumkuru",
        "Udupi",
        "Vijayawada",
        "Visakhapatnam",
        "Vizag",
        "Vizianagaram",
        "Wayanad",
        "West Godavari",
        "Yadgir",
    ],
    "South-T3": [
        "Joida",
        "Uttara Kannada",
    ],
    "Others": [
        "Lakshadweep",
        "Na",
        "Nan",
        "#N/A",
    ],
}

CITY_TO_BUCKET = {
    city: bucket
    for bucket, cities in CITY_BUCKET_MAP.items()
    for city in cities
}